spring:
  application:
    name: durain-order
  rabbitmq:
    host: 10.0.0.211
    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.0.0.211:3306/durain?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 10.0.0.211
    port: 6379
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ConnectTimeout:  10000
  ReadTimeout:  10000
env:  dev