spring:
  application:
    name: durain-games
  cloud:
    config:
      discovery:
        enabled: true
        service-id: BOOTU-CONFIG
      profile: dev
  rabbitmq:
    host: 10.0.0.211
    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/durain?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8861/eureka/