spring:
  jpa:
    show-sql: true
  redis:
    host: 10.0.0.211
    port: 6379
zuul:
  sensitive-headers: null
  routes:
    game-service:
      path: /game-service/**
      service-id: durain-games
    user-service:
      path: /user-service/**
      service-id: durain-user
    order-service:
      path: /order-service/**
      service-id: durain-order
management:
  endpoints:
    web:
      exposure:
        include: '*'